---  
- name: Install Mail Packages 
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb 
    - mariadb-server
    - mariadb-backup
    - python3-mysql
    - certbot 
    - dovecot 
    - dovecot-mysql 
    - dovecot-pigeonhole
    - postfix 
    - postfix-mysql 
    - postfix-pcre
    - fail2ban
