--- 
all: 
  hosts: 
    mailserver.host.com:
      ansible_user: fedora
      ansible_become: true
      ansible_become_method: sudo
  children: 
    mailservers: 
      hosts: 
        mailserver.host.com: